### ISSUE TITLE
may 05

### ISSUE THREAD

**Issue by SevlaMare** [ferbaco86/enumerables-ruby#3]
my_inject have a problem with the given arguments, will be fixed if you put some logic to define these args, it should work for:
``p (5..10).my_inject(1, :*) # 151200``
Your arguments in this way `my_inject(*args)` is correct, because the order can change, you can have (1, :+) or (:+), so define them inside the function.

**Comment by ferbaco86** [comment]
Solved! Thanks for the suggestion
